GLOBAL_PARAMS:
  name: "likelihood-atac-moe"
  task: 0
  num_features1: 3000
  num_features2: 5000
  cuda: true
  random_seed: 1
  log_save_interval: 10
  early_stopping_patience: 10 # If set to 0 or <0, early stopping is turned off.
  data1: "RNA"
  data2: "ATAC"
  data_path1: "/tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scatac/rna.npy"
  data_path2: "/tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scatac/atac.npy"
  data_features1: "/tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scatac/featureNamesRNA.npy"
  data_features2: "/tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scatac/featureNamesATAC.npy"
  sample_names: "/tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scatac/sampleNames.npy"
  labels: "/tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scatac/celltype_l2.npy"
  labelnames: "/tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scatac/celltypes_l2.npy"
  train_ind: "/tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scatac/trainInd.npy"
  val_ind: "/tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scatac/validInd.npy"
  test_ind: "/tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scatac/testInd.npy"
  nomics: 2
  log_inputs: true

MoE:
  epochs: 500
  batch_size: 64
  latent_dim: '128-64'
  lr: 0.0001
  likelihood1: 'nb'
  likelihood2: 'bernoulli'
  llikescale1: 1.0 
  llikescale2: 1.0
  train_loader_eval_batch_size: 64
  use_batch_norm: False
  dropout_probability: 0.1
  optimizer: 'Adam'
  beta_start_value: 1.
  enc_distribution: 'laplace'
  K: 20
  plot: False     # Flag for plotting training and validation losses (loss, recon loss and KL loss)



