GLOBAL_PARAMS:
  cuda: true
  data1: GE
  data2: CNV
  data_features1: /tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/genes_GE.npy
  data_features2: /tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/genes_CN.npy
  data_path1: /tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/GE.npy
  data_path2: /tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/CN.npy
  early_stopping_patience: 10
  labelnames: /tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/cancerTypes.npy
  labels: /tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/cancerType.npy
  log_save_interval: 10
  name: test_GE_CNV_moe
  nomics: 2
  num_features1: 5000
  num_features2: 5000
  random_seed: 1
  sample_names: /tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/sampleNames.npy
  task: 1
  test_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/testInd.npy
  train_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/trainInd.npy
  val_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/validInd.npy
MoE:
  K: 20
  batch_size: 64
  beta_start_value: 1.0
  dec1_lr: 0.0001
  dec2_lr: 0.0001
  dropout_probability: 0.1
  enc1_lr: 0.0001
  enc2_lr: 0.0001
  enc_distribution: laplace
  epochs: 500
  latent_dim: 256-128-32
  likelihood1: normal
  likelihood2: categorical
  llikescale1: 1.0
  llikescale2: 1.0
  lr: 0.0
  n_categories1: -1
  n_categories2: 5
  optimizer: Adam
  plot: false
  pre_trained: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/results/likelihood-tcga-moe-68_GE_CNV/MoE/checkpoint/model_best.pth.tar
  train_loader_eval_batch_size: 16
  use_batch_norm: false
