GLOBAL_PARAMS:
  cuda: true
  data1: RNA
  data2: ADT
  data_features1: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/featureNamesRNA.npy
  data_features2: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/featureNamesADT.npy
  data_path1: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/RNA.npy
  data_path2: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/ADT.npy
  early_stopping_patience: 10
  labelnames: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/celltypes_l3.npy
  labels: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/celltype_l3.npy
  log_save_interval: 10
  name: test_RNA_ADT_moe
  nomics: 2
  num_features1: 5000
  num_features2: 217
  random_seed: 1
  sample_names: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/sampleNames.npy
  task: 2
  test_ind: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/testInd.npy
  train_ind: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/trainInd.npy
  val_ind: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/validInd.npy
MoE:
  K: 10
  batch_size: 16
  beta_start_value: 1.0
  clf_criterion: mcc
  dec1_lr: 0.0001
  dec2_lr: 0.0001
  dropout_probability: 0.0
  enc1_lr: 0.0001
  enc2_lr: 0.0001
  enc_distribution: laplace
  epochs: 500
  latent_dim: 256-256-32
  likelihood1: nb
  likelihood2: nbm
  llikescale1: 1.0
  llikescale2: 1.0
  log_inputs: true
  lr: 0.0001
  optimizer: Adam
  pre_trained: results/tmpnbcite/results/likelihood-cite-moe-6_RNA_ADT/MoE/checkpoint/model_best.pth.tar
  train_loader_eval_batch_size: 64
  use_batch_norm: false
