CVAE:
  batch_size: 64
  beta_start_value: 1
  clf_criterion: mcc
  dropout_probability: 0.0
  enc_distribution: normal
  epochs: 500
  latent_dim: 256-64
  likelihood1: nb
  likelihood2: normal
  lr: 0.0001
  optimizer: Adam
  pre_trained: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/results/likelihood-cite-cvae-5_RNA_ADT/CVAE/checkpoint/model_best.pth.tar
  train_loader_eval_batch_size: 64
  use_batch_norm: false
GLOBAL_PARAMS:
  cuda: true
  data1: RNA
  data2: ADT
  data_features1: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_RNA_5000MAD_featureNames.npy
  data_features2: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_ADT_5000MAD_featureNames.npy
  data_path1: /tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/RNA.npy
  data_path2: /tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/ADT.npy
  early_stopping_patience: 10
  labelnames: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_ADT_5000MAD_cellTypes_l3.npy
  labels: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_ADT_5000MAD_cellType_l3.npy
  log_save_interval: 10
  name: test_RNA_ADT_cvae
  nomics: 2
  num_features1: 5000
  num_features2: 224
  random_seed: 1
  sample_names: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_RNA_5000MAD_sampleNames.npy
  task: 2
  test_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/task1/testInd.npy
  train_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/task1/trainInd.npy
  val_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/task1/validInd.npy
  level: l3
