GLOBAL_PARAMS:
  cuda: true
  data1: RNA
  data2: ADT
  data_features1: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_RNA_5000MAD_featureNames.npy
  data_features2: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_ADT_5000MAD_featureNames.npy
  data_path1: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_RNA_5000MAD.npy
  data_path2: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_ADT_5000MAD.npy
  early_stopping_patience: 10
  labelnames: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_RNA_5000MAD_cellType.npy
  labels: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_RNA_5000MAD_cellType.npy
  log_save_interval: 10
  name: test_RNA_ADT_mvib
  num_features1: 5000
  num_features2: 224
  random_seed: 1
  sample_names: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_RNA_5000MAD_sampleNames.npy
  task: 2
  test_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/task1/testInd.npy
  train_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/task1/trainInd.npy
  val_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/task1/validInd.npy
MVIB:
  batch_size: 64
  beta: 1.0
  clf_criterion: mcc
  dec1_lr: 1.0e-05
  dec2_lr: 1.0e-05
  dropout_probability: 0.0
  enc1_last_activation: none
  enc1_lr: 1.0e-05
  enc1_output_scale: 1.0
  enc2_last_activation: none
  enc2_lr: 1.0e-05
  enc2_output_scale: 1.0
  enc_distribution: normal
  epochs: 500
  latent_dim: '64'
  mi_net_arch: 500-100-1
  mi_net_lr: 1.0e-05
  optimizer: Adam
  pre_trained: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/results/train-cite-mvib-41_RNA_ADT/MVIB/checkpoint/model_epoch170.pth.tar
  train_loader_eval_batch_size: 64
  use_batch_norm: false
