CGAE:
  batch_size: 32
  beta_start_value: 1.0
  clf_criterion: acc
  crossPenaltyCoef: 1.0
  dec1_lr: 0.001
  dec2_lr: 0.001
  dropout_probability: 0.0
  enc1_last_activation: none
  enc1_lr: 0.001
  enc1_output_scale: 1.0
  enc2_last_activation: none
  enc2_lr: 0.001
  enc2_output_scale: 1.0
  epochs: 400
  latent_dim: '1'
  loss_function: mse
  optimizer: Adam
  use_batch_norm: false
  zconstraintCoef: 1.0
GLOBAL_PARAMS:
  cuda: true
  data1: v1
  data2: v2
  data_features1: synthetic-data/dataset1/view1_features.npy
  data_features2: synthetic-data/dataset1/view2_features.npy
  data_path1: synthetic-data/dataset1/view1.npy
  data_path2: synthetic-data/dataset1/view2.npy
  early_stopping_patience: 10
  labelnames: synthetic-data/dataset1/labelnames.npy
  labels: synthetic-data/dataset1/labels.npy
  log_save_interval: 5
  name: experiment
  num_features1: 3
  num_features2: 3
  random_seed: 1
  sample_names: synthetic-data/dataset1/samples.npy
  task: 0
  test_ind: synthetic-data/dataset1/testInd.npy
  train_ind: synthetic-data/dataset1/trainInd.npy
  val_ind: synthetic-data/dataset1/validInd.npy
