CGAE:
  batch_size: 64
  beta_start_value: 1
  clf_criterion: acc
  crossPenaltyCoef: 1
  dec1_lr: 0.0001
  dec2_lr: 0.0001
  dropout_probability: 0.1
  enc1_last_activation: none
  enc1_lr: 0.0001
  enc1_output_scale: 1.0
  enc2_last_activation: none
  enc2_lr: 0.0001
  enc2_output_scale: 1.0
  enc_distribution: normal
  epochs: 500
  latent_dim: 256-128-64
  loss_function: mse
  optimizer: Adam
  use_batch_norm: false
  zconstraintCoef: 1
GLOBAL_PARAMS:
  cuda: true
  data1: GE
  data2: ME
  data_features1: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/GE_featureNames.npy
  data_features2: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/ME_featureNames.npy
  data_path1: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/GE.npy
  data_path2: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/ME.npy
  early_stopping_patience: 10
  labelnames: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/cancerTypes.npy
  labels: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/cancerType.npy
  log_save_interval: 10
  name: train-tcga-cgae-29
  num_features1: 5000
  num_features2: 5000
  random_seed: 1
  sample_names: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/sampleNames.npy
  task: 0
  test_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/task1/testInd.npy
  train_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/task1/trainInd.npy
  val_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/task1/validInd.npy
