GLOBAL_PARAMS:
  nomics: 2
  name: "likelihood-tcga-cvae"
  task: 0
  num_features1: 5000
  num_features2: 5000
  cuda: true
  random_seed: 1
  log_save_interval: 10
  early_stopping_patience: 10 # If set to 0 or <0, early stopping is turned off.
  data1: "GE"
  data2: "ME"
  data_path1: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/GE.npy"
  data_path2: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/ME.npy"
  data_features1: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/GE_featureNames.npy"
  data_features2: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/ME_featureNames.npy"
  sample_names: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/sampleNames.npy"
  labels: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/cancerType.npy"
  labelnames: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/cancerTypes.npy"
  train_ind: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/trainInd.npy"
  val_ind: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/validInd.npy"
  test_ind: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/testInd.npy"

CVAE:
  epochs: 500
  batch_size: 64
  latent_dim: '128'
  lr: 0.0001
  likelihood1: 'normal'
  likelihood2: 'beta'
  use_batch_norm: False
  dropout_probability: 0.0
  optimizer: 'Adam'
  beta_start_value: 1
  enc_distribution: 'normal'
  train_loader_eval_batch_size: 64
