GLOBAL_PARAMS:
  name: "likelihood-tcga-mvib"
  task: 0
  num_features1: 5000
  num_features2: 5000
  cuda: true
  random_seed: 1
  log_save_interval: 10
  early_stopping_patience: 10 # If set to 0 or <0, early stopping is turned off.
  data1: "GE"
  data2: "ME"
  data_path1: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/GE.npy"
  data_path2: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/ME.npy"
  data_features1: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/GE_featureNames.npy"
  data_features2: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/ME_featureNames.npy"
  sample_names: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/sampleNames.npy"
  labels: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/cancerType.npy"
  labelnames: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/cancerTypes.npy"
  train_ind: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/trainInd.npy"
  val_ind: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/validInd.npy"
  test_ind: "/tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/testInd.npy"


MVIB:
  epochs: 500
  batch_size: 64
  latent_dim: '64'
  clf_criterion: 'acc'
  enc1_lr: 0.0001
  enc2_lr: 0.0001
  mi_net_lr: 0.0001
  use_batch_norm: False
  dropout_probability: 0.0
  optimizer: 'Adam'
  enc1_output_scale: 1.
  enc2_output_scale: 1.
  enc1_last_activation: 'none'
  enc2_last_activation: 'none'
  mi_net_arch: '100-1'
  beta: 1.
  enc_distribution: 'normal'
