GLOBAL_PARAMS:
  cuda: true
  data1: GE
  data2: ME
  data_features1: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/GE_featureNames.npy
  data_features2: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/ME_featureNames.npy
  data_path1: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/GE.npy
  data_path2: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/ME.npy
  early_stopping_patience: 10
  labelnames: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/cancerTypes.npy
  labels: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/cancerType.npy
  log_save_interval: 10
  name: train-tcga-mvib-40
  num_features1: 5000
  num_features2: 5000
  random_seed: 1
  sample_names: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/sampleNames.npy
  task: 0
  test_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/task1/testInd.npy
  train_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/task1/trainInd.npy
  val_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/task1/validInd.npy
MVIB:
  batch_size: 64
  beta: 1.0
  clf_criterion: acc
  dec1_lr: 1.0e-05
  dec2_lr: 1.0e-05
  dropout_probability: 0.0
  enc1_last_activation: none
  enc1_lr: 1.0e-05
  enc1_output_scale: 1.0
  enc2_last_activation: none
  enc2_lr: 1.0e-05
  enc2_output_scale: 1.0
  enc_distribution: normal
  epochs: 500
  latent_dim: '32'
  mi_net_arch: 500-100-1
  mi_net_lr: 1.0e-05
  optimizer: Adam
  use_batch_norm: false
