GLOBAL_PARAMS:
  name: "train-tcga-geme-cgae"
  task: 0
  num_features1: 5000
  num_features2: 5000
  cuda: true
  random_seed: 1
  log_save_interval: 10
  early_stopping_patience: 10 # If set to 0 or <0, early stopping is turned off.
  data1: "GE"
  data2: "ME"
  data_path1: "/home/bram/jointomicscomp/data/GE.npy"
  data_path2: "/home/bram/jointomicscomp/data/ME.npy"
  data_features1: "/home/bram/jointomicscomp/data/GE_featureNames.npy"
  data_features2: "/home/bram/jointomicscomp/data/ME_featureNames.npy"
  sample_names: "/home/bram/jointomicscomp/data/sampleNames.npy"
  labels: "/home/bram/jointomicscomp/data/cancerType.npy"
  labelnames: "/home/bram/jointomicscomp/data/cancerTypes.npy"
  train_ind: "/home/bram/jointomicscomp/data/task1/trainInd.npy"
  val_ind: "/home/bram/jointomicscomp/data/task1/validInd.npy"
  test_ind: "/home/bram/jointomicscomp/data/task1/testInd.npy"

CGAE:
  epochs: 10
  batch_size: 64
  latent_dim: '128'
  clf_criterion: 'acc'
  enc1_lr: 0.0001
  dec1_lr: 0.0001
  enc2_lr: 0.0001
  dec2_lr: 0.0001
  loss_function: 'mse'
  use_batch_norm: False
  dropout_probability: 0.0
  optimizer: 'Adam'
  enc1_output_scale: 1.
  enc2_output_scale: 1.
  enc1_last_activation: 'none'
  enc2_last_activation: 'none'
  beta_start_value: 1
  zconstraintCoef: 1
  crossPenaltyCoef: 1
  enc_distribution: 'normal'
