batch_size: 64
lr: 0.0001
epochs: 150
early_stopping_patience: 10
log_save_interval: 10
num_features1: 217
random_seed: 1
checkpoint: './type-classifier/ADT/checkpoint'
log: './type-classifier/ADT/log'
log_transform: True

data_path: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/ADT.npy
labels: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/celltype.npy
test_ind: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/testInd.npy
train_ind: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/trainInd.npy
val_ind: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/validInd.npy
