batch_size: 64
lr: 0.0001
epochs: 150
data_path: /tudelft.net/staff-bulk/ewi/insy/DBL/smakrod/lb/tcga-download/data/datasets/ge-me-cn-2022-04-16/RNA.npy
early_stopping_patience: 10
labels: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_RNA_5000MAD_cellType.npy
log_save_interval: 10
num_features1: 5000
random_seed: 1
test_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/task1/testInd.npy
train_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/task1/trainInd.npy
val_ind: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/task1/validInd.npy
checkpoint: './type-classifier/RNA/checkpoint'
log: './type-classifier/RNA/log'
