batch_size: 64
lr: 0.0001
epochs: 150
data_path: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scatac/rna.npy
early_stopping_patience: 10
labels: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scatac/celltype.npy
log_save_interval: 10
num_features1: 3000
random_seed: 1
test_ind: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scatac/testInd.npy
val_ind: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scatac/validInd.npy
train_ind: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scatac/trainInd.npy
checkpoint: './type-classifier/RNA2/checkpoint'
log: './type-classifier/RNA2/log'
