GLOBAL_PARAMS:
  name: "train-cite-poe"
  task: 0
  num_features1: 5000
  num_features2: 224
  cuda: true
  random_seed: 1
  log_save_interval: 10
  early_stopping_patience: 10 # If set to 0 or <0, early stopping is turned off.
  data1: "RNA"
  data2: "ADT"
  data_path1: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_RNA_5000MAD.npy"
  data_path2: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_ADT_5000MAD.npy"
  data_features1: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_RNA_5000MAD_featureNames.npy"
  data_features2: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_ADT_5000MAD_featureNames.npy"
  sample_names: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_RNA_5000MAD_sampleNames.npy"
  labels: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_RNA_5000MAD_cellType.npy"
  labelnames: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_RNA_5000MAD_cellType.npy"
  train_ind: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/task1/trainInd.npy"
  val_ind: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/task1/validInd.npy"
  test_ind: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/task1/testInd.npy"

PoE:
  epochs: 500
  batch_size: 64
  latent_dim: '128-64'
  clf_criterion: 'acc'
  loss_function: 'mse'
  use_batch_norm: False
  dropout_probability: 0.0
  optimizer: 'Adam'
  plot: False     # Flag for plotting training and validation losses (loss, recon loss and KL loss)
  pre_trained: ""
  lr: 0.0001
  train_loader_eval_batch_size: 64
