GLOBAL_PARAMS:
  name: "train-sc"
  task: 0
  num_features1: 5000
  num_features2: 224
  cuda: true
  random_seed: 1
  log_save_interval: 3
  early_stopping_patience: 10 # If set to 0 or <0, early stopping is turned off.
  data1: "RNA"
  data2: "ADT"
  data_path1: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_RNA_5000MAD.npy"
  data_path2: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_ADT_5000MAD.npy"
  data_features1: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_RNA_5000MAD_featureNames.npy"
  data_features2: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_ADT_5000MAD_featureNames.npy"
  sample_names: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/cell_sampleNames.npy"
  labels: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_ADT_5000MAD_cellType.npy"
  labelnames: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_ADT_5000MAD_cellTypes.npy"
  train_ind: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/trainInd.npy"
  val_ind: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/validInd.npy"
  test_ind: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/testInd.npy"

CGAE:
  epochs: 10
  latent_dim: '32'
  batch_size: 64
  enc1_lr: 0.0001
  dec1_lr: 0.0001
  enc2_lr: 0.0001
  dec2_lr: 0.0001
  loss_function: 'mse'
  use_batch_norm: True
  dropout_probability: 0.0
  optimizer: 'Adam'
  enc1_output_scale: 1.
  enc2_output_scale: 1.
  enc1_last_activation: 'none'
  enc2_last_activation: 'none'
  beta_start_value: 1
  zconstraintCoef: 1
  crossPenaltyCoef: 1
  enc_distribution: 'normal'
