totalVI:
  batch_size: 64
  beta_start_value: 1
  dropout_probability: 0.0
  lr: 0.001
  enc_distribution: normal
  epochs: 500
  zdim: 32
  n_layers: 1
  n_neurons_per_layer: 128
  optimizer: Adam
  train_loader_eval_batch_size: 64
  use_batch_norm: false
GLOBAL_PARAMS:
  cuda: true
  data1: RNA
  data2: ADT
  mudata_path: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/
  labelnames: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/celltypes_l3.npy
  labels: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/celltype_l3.npy
  log_save_interval: 10
  name: likelihood-cite-totalvi-test
  nomics: 2
  num_features1: 5000
  num_features2: 217
  random_seed: 1
  # sample_names: /tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/CELL/pbmc_multimodal_RNA_5000MAD_sampleNames.npy
  task: 0
  test_ind: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/testInd.npy
  train_ind: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/trainInd.npy
  val_ind: /tudelft.net/staff-umbrella/liquidbiopsy/neural-nets/jointomicscomp/data/scvi-cite/validInd.npy
