GLOBAL_PARAMS:
  name: "train-tcga-poe"
  task: 0
  num_features1: 5000
  num_features2: 5000
  cuda: true
  random_seed: 1
  log_save_interval: 10
  early_stopping_patience: 10 # If set to 0 or <0, early stopping is turned off.
  data1: "GE"
  data2: "CNV"
  data_path1: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/GE.npy"
  data_path2: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/GCN.npy"
  data_features1: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/GE_featureNames.npy"
  data_features2: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/GCN_featureNames.npy"
  sample_names: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/sampleNames.npy"
  labels: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/cancerType.npy"
  labelnames: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/cancerTypes.npy"
  train_ind: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/task1/trainInd.npy"
  val_ind: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/task1/validInd.npy"
  test_ind: "/tudelft.net/staff-bulk/ewi/insy/DBL/bpronk/jointomicscomp/data/task1/testInd.npy"


PoE:
  epochs: 500
  batch_size: 64
  latent_dim: '128-64'
  clf_criterion: 'acc'
  loss_function: 'mse'
  use_batch_norm: False
  dropout_probability: 0.0
  optimizer: 'Adam'

  plot: False     # Flag for plotting training and validation losses (loss, recon loss and KL loss)

  # Model optionsmain.yaml
  pre_trained: ""
  lr: 0.0001
